[package]
name = "pods"
version = "0.1.0"
authors = ["Marcus Behrendt <marcus.behrendt.86@gmail.com>"]
edition = "2021"

[dependencies]
adw = { version = "0.1", package = "libadwaita", features = ["gtk_v4_6"] }
anyhow = "1"
cascade = "1"
futures = { version = "0.3", default-features = false }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.4", package = "gtk4", features = ["v4_6"] }
indexmap = "1.7"
log = "0.4"
names = { version = "0.13", default-features = false }
once_cell = "1.9"
paste = "1.0"
podman-api = { git = "https://github.com/marhkb/podman-api-rs.git", branch = "staging", default-features = false }
serde = "1.0"
sourceview5 = "0.4"
syslog = "6.0"
tokio = { version = "1", features = ["process", "rt-multi-thread"] }
vte = "0.10"
