[package]
name = "symphony"
version = "0.1.0"
authors = ["Marcus Behrendt <marcus.behrendt.86@gmail.com>"]
edition = "2021"

[dependencies]
adw = { version = "0.1", package = "libadwaita" }
futures = { version = "0.3", default-features = false }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.4", package = "gtk4" }
indexmap = "1.7"
log = "0.4"
once_cell = "1.9"
paste = "1.0"
podman-api = "0.1"
syslog = "6.0"
tokio = { version = "1", features = ["process", "rt-multi-thread"] }
