[package]
name = "symphony"
version = "0.1.0"
authors = ["Marcus Behrendt <marcus.behrendt.86@gmail.com>"]
edition = "2021"

[dependencies]
adw = { version = "0.1", package = "libadwaita" }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = {version = "0.4", package = "gtk4"}
log = "0.4"
once_cell = "1.9"
syslog = "6.0"
