[package]
name = "pods"
version = "0.1.0"
authors = ["Marcus Behrendt <marcus.behrendt.86@gmail.com>"]
edition = "2021"

[dependencies]
adw = { version = "0.1", package = "libadwaita", features = ["gtk_v4_6"] }
cascade = "1"
futures = { version = "0.3", default-features = false }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.4", package = "gtk4", features = ["v4_6"] }
indexmap = "1.7"
log = "0.4"
once_cell = "1.9"
paste = "1.0"
podman-api = { git = "https://github.com/vv9k/podman-api-rs.git", default-features = false }
syslog = "6.0"
tokio = { version = "1", features = ["process", "rt-multi-thread"] }
vte = "0.10"
